name: build-win-linux

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [ "published" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: PortuinoIDE-Windows
            data_sep: ';'
          - os: ubuntu-22.04
            artifact_name: PortuinoIDE-Linux
            data_sep: ':'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements-build.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt

      # Build (Windows)
      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $iconArg = ""
          if (Test-Path "icons\portuino.ico") { $iconArg="--icon=icons\portuino.ico" }

          pyinstaller --noconsole --name PortuinoIDE $iconArg `
            --paths . `
            --hidden-import portuino_compiler `
            --hidden-import interpretador_portuino `
            --add-data "icons;icons" `
            --add-data "manual_portuino.md;." `
            --clean ide_portuino.py

      # Build (Linux)
      - name: Build with PyInstaller (Linux)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          iconArg=""
          if [ -f "icons/portuino.png" ]; then
            iconArg="--icon=icons/portuino.png"
          fi

          pyinstaller --noconsole --name PortuinoIDE $iconArg             --paths .             --hidden-import portuino_compiler             --hidden-import interpretador_portuino             --add-data "icons:icons"             --add-data "manual_portuino.md:."             --clean ide_portuino.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/PortuinoIDE/

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/PortuinoIDE/**
